#!/bin/zsh

# # # # # # # # # # # # #
#    Alias Config     #
# # # # # # # # # # # # #

alias open='xdg-open'

# Buildout
alias pin='bin/instance'
alias pbo='bin/buildout'
# Instance
alias pinf='bin/instance fg'

# Basic Builtin
alias la='ls -lAhX --color'
alias lt='ls -lAht --color'
alias ls='ls -GhX --color'
alias ll='ls -lX --color'
alias grep='grep --color'
alias rmf='rm -rf'

# Aptitude
alias update='sudo apt update'
alias upgrade='sudo apt upgrade'

# GIT
# rebase
alias grc='git rebase --continue'
alias gri='git rebase -S -i'
alias gra='git rebase --abort'
# commit
alias gca='git commit -S --all --amend --no-edit'
alias gc='git commit -S -m'
# push
alias gpf='git push --sign=if-asked --force'
alias gp='git push --sign=if-asked'
# misc
alias glog='git log --graph'
alias gcp='git cherry-pick -S '
alias gco='git checkout'
alias gst='git status'
alias gpu='git pull'

# Misc
alias fsize='du -sh' # Show dictionary size
